### PR TITLE
JuliaFEM + MFrontInterface part in JOSS paper

### PR DESCRIPTION
**Pull request by TeroFrondelius**
@IvanYashchuk please push `3dbeam_mfront.png` picture here. I will invite you as a contributor.

### CODE REVIEW

**Comment by TeroFrondelius** [comment]
Please, don't merge. I need to learn to use the git better. Any advice how to fix this is really welcome.

**Comment by TeroFrondelius** [comment]
I somehow fucked up the `git merge master` command. How can I go back and fix it?

**Comment by thelfer** [comment]
Ok, let me know when you're ready. If needed, open a new pull request and close this one.

**Comment by TeroFrondelius** [comment]
@thelfer I don't know what happened. I thought I restarted from master. Can you check those changes to the bib file. I have a feeling I try to push back some old changes.

**Comment by TeroFrondelius** [comment]
Now I did everything correctly and still so many bib file changes. Maybe my Atom editor doesn't like the file.

**Comment by thelfer** [comment]
Indeed, the new bib file seems quite messy. Can you checkout the current version of `bibliography.bib` and use another editor ?

**Pull request merged**
